name: EasyMapReset
authors: [D3SOX, earomc]
version: 1.0.5-SNAPSHOT
description: A map reset plugin
main: net.earomc.easymapreset.EasyMapReset
loadbefore: [Multiverse-Core]
commands:
  easymapreset:
    description: "EasyMapReset base command."
    permission: "earomc.easymapreset"
    aliases:
      - "emr"